name = "TBS-Server"
author = "Slash"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2989f130825bdb8ff778b808b5446c6a77958e185b25cc1507698e82faab9103"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
