name = "TBS-Server"
author = "Slash"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6e22910282702043959345ba4095b82cdc23ba0674e7e14acb35ef8a7bb70f62"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"
